---
 - name: Install sudo
   apt: name=sudo state=present update_cache=yes

 - name: Ensure managment user is added
   user: name={{user}} comment="Managment User" uid="{{UID}}" shell=/bin/bash

 - name: Adding managment user to sudoers file
   lineinfile: dest=/etc/sudoers regexp='^{{user}}' line='{{user}} ALL=(ALL) NOPASSWD:ALL' state=present backup=yes

 - name: Ensure public key is copied to the server
   authorized_key: user={{ item.name }} key="{{ item.key }}"
   with_items: "{{ssh_keys}}"
