---
- hosts: mail-cloud
  remote_user: techie
  vars:
    TZ: Asia/Kolkata
    user: techie
    base_dir: myapps
    docker_dir: "/home/{{ansible_user}}/{{base_dir}}"

  roles:
    - common
    - backup   
